package vocabulary

/**
	A delayed routine call, whose arguments may be open, partially closed or closed.
	Generated by special reference to a routine, usually via a dedicated keyword,
	such as 'lambda' or 'agent', or other special syntax. Instances may include
	closed delayed calls like calculate_age (dob="1987-09-13", today="2019-06-03")
	but also partially open calls such as format_structure (struct=?, style=3) ,
	where struct is an open argument. Evaluation type (i.e. type of runtime
	evaluated form) is BMM_SIGNATURE .
*/

type IElAgent interface {
	/**
		Eval type is the signature corresponding to the (remaining) open arguments and
		return type, if any.
	*/
	eval_type (): BMM_ROUTINE_TYPE  Post_result : Result = definition.signature (  )  BMM_ROUTINE_TYPE  Post_result : Result = definition.signature
// True if there are no open arguments.
	is_callable (): Boolean  Post_result_validity : Result = open_arguments = Void (  )  Boolean  Post_result_validity : Result = open_arguments = Void
// Generated full reference name, including scoping elements.
	reference (): String (  )  String
}

type ElAgent struct {
}
