package vocabulary

/**
	A delayed routine call, whose arguments may be open, partially closed or closed.
	Generated by special reference to a routine, usually via a dedicated keyword,
	such as 'lambda' or 'agent', or other special syntax. Instances may include
	closed delayed calls like calculate_age (dob="1987-09-13", today="2019-06-03")
	but also partially open calls such as format_structure (struct=?, style=3) ,
	where struct is an open argument. Evaluation type (i.e. type of runtime
	evaluated form) is BMM_SIGNATURE .
*/

type IElAgent interface {
	EvalType (  )  BMM_ROUTINE_TYPE  Post_result : Result = definition.signature
	IsCallable (  )  Boolean  Post_result_validity : Result = open_arguments = Void
	Reference (  )  string
}

type ElAgent struct {
}
